### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by maroxtn**

### CODE REVIEW

**Review by pablo-tech — CHANGES_REQUESTED** [review]
hey great work; some feedback:
- please put together things that go together.  If a folder has a notebook, and the notebook depends on data files, please put the data files in the same folder.  
- please add minimal context for each line of code.  For example, it is not immediately evident what these are: iseasse, turkcorpus.  For now, no need to explain code itself, more like context and intention of what the code will try to do
- right now it seems it is intended that the code replicates the results of table 2, but this is not clear.  I see some numbers, but it is not evident what is being tested, the table has a number of rows and columns, is the calculation for each provided somewhere? And if so, where does this come from

**Comment by maroxtn** [comment]
- The idea behind leaving the data in a folder by itself is that the data is going to be used by multiple notebooks existing in more than one folder; if we copy the data to each of those folders, we'd have multiple copies of the same dataset in the same repo. 
- I added that now
- I also added details to the notebook now. Just a note, for the Turkcorpus, I did not get the results as the paper, it seems that there multiple versions of Turkcorpus, and they did not specify in the paper which one they used.

**Review by pablo-tech — CHANGES_REQUESTED** [review]
Questions:
- who has edit rights over the colabs? Should we create a user that does this, so we don't delete the content by accident in the future?
- please put the screenshot of the table right next to the description of the metrics and libraries
- please put the descriptions in the same order as in the screenshot of the paper: a) Asset, b) Turk, c) Newsela
- they mention a "mining procedure" in the paper.  Is there a simple colab that would demonstrate what that is?
- do MUSS publish their training code? Specifically they mention an adaptation of ACCESS
- is there any other key part you can think of we should capture?

**Comment by maroxtn** [comment]
- For now, only me who can edit the notebook. Everyone else could clone it and make their own changes and save it elsewhere. I can share it with you and transfer the editing rights to you.
- Done
- Done
- The mining procedure is the algorithm that they used for finding sentences for simplification. It is publicly available in the repo, but I am not sure exactly how would I demonstrate that. Should I use it on a dummy text dump to mine for paraphrases for example ? 
- Yes the training code is available. Yes they mentioned an adaptation of ACCESS to control the output of the model.
- I would suggest having a notebook for training MUSS,  further fine tune MUSS, or to use ACCESS to control the sentence. They said in the paper "we use ACCESS (Martin et al., 2020) to control attributes such as length, lexical and syntactic complexity"". In their codebase they didn't demonstrate that, so maybe I can look into that.

**Comment by pablo-tech** [comment]
@maroxtn:
- after we're done with milestone, pls transfer all edit rights to edu@pablotech.uno
- yes please showcase the "mining procedure" by applying on a small variety of text examples
- yes please try train/finetune MUSS; or attempt to train ACCESS to do the same per MUSS suggestions.  Ideally this does not require looking at "Martin et al" from scratch (that would be a different issue/milestone).  Yes the idea is to demonstrate to "control attributes such as length, lexical and syntactic complexity"

**Pull request merged**
